
import Head from 'next/head';
import Link from 'next/link';
import React, { useRef, useState } from 'react'
import { useRouter } from 'next/router'
import { marked } from 'marked';
import DOMPurify from 'dompurify';
import parse from 'html-react-parser';

const Post = () => {
    const titleRef = useRef(null)
    const authorRef = useRef(null)
    const contentRef = useRef(null)
    const passwordRef = useRef(null)
    const router = useRouter()
    const [preview, setPreview] = useState(null)
    const handleSubmit = async (e) => {
        e.preventDefault()
        console.log(titleRef.current.value)
        const res = await fetch('/api/post/', {
            method: 'POST',
            body: JSON.stringify({
                title: titleRef.current.value,
                content: contentRef.current.value,
                password: passwordRef.current.value
            }),
            headers: {
                'Content-Type': 'application/json',
            },
        })
        const data = await res.json()
        if(data.status === 201){alert("Post created!")}
        if(data.status === 403){alert("Wrong Password")}
        router.push('/')
    }

    const handleChange = () => {
        const markedPreview = marked.parse(contentRef.current.value)
        const clean = DOMPurify.sanitize(markedPreview)
        setPreview(clean)
    }

    return (
        <>
            <Head>
                <title>Rndm Blog</title>
                <meta name="description" content="Random blog generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="pt-8 pb-16 lg:pt-16 lg:pb-24 min-h-screen bg-gradient-to-b from-[#2e026d] to-[#15162c]">
                <div className="flex justify-between px-4 mx-auto max-w-screen-xl ">
                    <article className="mx-auto w-full max-w-2xl">
                        <header className="mb-4 lg:mb-6 ">
                            <div className="text-white/80 mb-8">
                                <Link href="/">&#60;&#60; Back to Home</Link>
                            </div>
                        </header>
                        <form onSubmit={handleSubmit}>
                            <div className="text-white">
                                <h1 className="p-2 mb-2 text-3xl">Post your article</h1>
                                <h3 className="p-2 mb-2">You can write in markdown or raw html</h3>
                            </div>
                            <div className="text-white w-full space-y-4 inline-flex flex-col">
                                <div className="inline-flex flex-col items-center justify-start">
                                    <span>Title</span><input ref={titleRef} name="title" placeholder="title" className="text-black p-2 bg-white rounded-lg" type="text" />
                                </div>
                                <div className="inline-flex flex-col items-center justify-start">
                                    <span>Author</span><input ref={authorRef} name="author" placeholder="Alice" disabled className="text-black p-2 bg-white rounded-lg" type="text" />
                                </div>
                                <div className="inline-flex flex-col items-center justify-start">
                                    <span>Content</span>
                                    <textarea
                                        ref={contentRef}
                                        name="content"
                                        className="p-2 text-black rounded-lg"
                                        placeholder="content" name="content"
                                        cols="60"
                                        rows="20"
                                        onChange={handleChange}
                                    >
                                    </textarea>
                                </div>
                                <div className="inline-flex flex-col items-center justify-start">
                                    <span>Password  for posting</span>
                                    <input 
                                    ref={passwordRef}
                                    type="password"
                                    name="password"
                                    className="p-2 text-black rounded-lg" 
                                    />
                                </div>
                                <div className="inline-flex justify-center">
                                    <button
                                        type="submit"
                                        className="p-2 bg-white/40 rounded-lg"
                                    >POST</button>
                                </div>
                            </div>
                        </form>
                    </article>
                </div>
                <div className="flex justify-between px-4 mx-auto max-w-screen-xl ">
                    <article className="mx-auto w-full max-w-2xl">
                        <h1 className="text-3xl text-white">Preview</h1>
                        <div className="text-white bg-black/10">
                            {preview != null ? parse(preview) : null}
                        </div>

                    </article>
                </div>
            </main>
        </>
    );
};

export default Post